// Other Courses/React/Page Transitions In React - React Router V6 and Framer Motion Tutorial/transition/src/pages/About.jsx
const About = () => {
  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
      <div>
        <h1>About us</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet architecto at consectetur cupiditate dicta ea
           explicabo facilis, mollitia, quasi, rerum sapiente sed voluptate voluptatum. Ab aspernatur iste natus
           nesciunt veniam.</p>
      </div>
    </motion.div>
  )
};

export default About;

// Udemy/Vuetify Create an App with Vue JS and Vuex - in 5 Hours/vuetify-todo/src/views/About.vue
<template>
  <div class="about pa-6">
    <h1>About Vuetify Todo</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, in inventore nam quos ut vel voluptatum. Accusantium animi dicta ex explicabo fuga laudantium vitae? Laudantium libero nemo placeat soluta ut.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, in inventore nam quos ut vel voluptatum. Accusantium animi dicta ex explicabo fuga laudantium vitae? Laudantium libero nemo placeat soluta ut.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, in inventore nam quos ut vel voluptatum. Accusantium animi dicta ex explicabo fuga laudantium vitae? Laudantium libero nemo placeat soluta ut.</p>

  </div>
</template>
