// Other Courses/Typescript/Typescript Masterclass - netninja/6-using-typescript-with-nextjs/ninja-blog/src/app/about/page.tsx
const About = () => {
  return (
    <main>
      <h2>About</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum fugit iusto laborum officiis quam quis quos, sapiente soluta! Animi, doloremque?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquam animi consectetur consequatur dicta doloremque eaque eum illum labore minima necessitatibus neque odit perferendis quo saepe, sint, suscipit ullam voluptatum!</p>
    </main>
  );
};

export default About;

// Udemy/Vuetify Create an App with Vue JS and Vuex - in 5 Hours/vuetify-todo/src/views/About.vue
<template>
  <div class="about pa-6">
    <h1>About Vuetify Todo</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, in inventore nam quos ut vel voluptatum. Accusantium animi dicta ex explicabo fuga laudantium vitae? Laudantium libero nemo placeat soluta ut.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, in inventore nam quos ut vel voluptatum. Accusantium animi dicta ex explicabo fuga laudantium vitae? Laudantium libero nemo placeat soluta ut.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, in inventore nam quos ut vel voluptatum. Accusantium animi dicta ex explicabo fuga laudantium vitae? Laudantium libero nemo placeat soluta ut.</p>

  </div>
</template>
