// Udemy/Build Web Apps with Vue JS 3 and Firebase/Section 16 - PROJECT BUILD - Muso Ninjas/muso-ninjas/src/views/auth/Login.vue
<template>
  <form @submit.prevent="handleSubmit">
    <h3>Log In</h3>
    <input type="email" placeholder="Email" v-model="email">
    <input type="password" placeholder="Password" v-model="password">
    <div v-if="error" class="error">{{error}}</div>
    <button v-if="!isPending">Log in</button>
    <button v-if="isPending" disabled>Loading</button>
  </form>
</template>

<script>
  import useLogin from "../../composables/useLogin";
  import {ref} from "vue";


  export default {
    name: "Login",
    setup() {
      const {error, login, isPending} = useLogin();
      const email = ref("");
      const password = ref("");

      const handleSubmit = async () => {
        const res = await login(email.value, password.value);
        if (!error.value) {
          console.log("user logged in");
        }
      }

      return {email, password, handleSubmit, error, isPending}
    }
  }
</script>

<style scoped>

</style>

// Other Courses/React/MERN Stack Tutorial/frontend/src/pages/Login.jsx
import React, { useState } from 'react';
import { useLogin } from "../hooks/useLogin";


const Login = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const { login, error, isLoading } = useLogin();

  const handleSubmit = async (e) => {
    e.preventDefault();

    await login(email, password);
  };

  return (
    <form className="login" onSubmit={handleSubmit}>
      <h3>Log in</h3>

      <label>Email:</label>
      <input
        type="email"
        onChange={(e) => setEmail(e.target.value)}
        value={email}
      />

      <label>Password:</label>
      <input
        type="password"
        onChange={(e) => setPassword(e.target.value)}
        value={password}
      />

      <button disabled={isLoading}>Log in</button>
      {error && <div className="error">{error}</div>}
    </form>
  );
};

export default Login;
