// Udemy/Build Web Apps with Vue JS 3 and Firebase/Section 16 - PROJECT BUILD - Muso Ninjas/muso-ninjas/src/views/auth/Signup.vue
<template>
  <form @submit.prevent="handleSubmit">
    <h3>Sign Up</h3>
    <input type="text" placeholder="Display name" v-model="displayName">
    <input type="email" placeholder="Email" v-model="email">
    <input type="password" placeholder="Password" v-model="password">
    <div v-if="error" class="error">{{error}}</div>
    <button v-if="!isPending">Sign up</button>
    <button v-if="isPending" disabled>Loading</button>
  </form>
</template>

<script>
  import {ref} from "vue";
  import useSignup from "../../composables/useSignup";
  import {useRouter} from "vue-router";


  export default {
    name: "Signup",
    setup() {
      const {error, signup, isPending} = useSignup();
      const router = useRouter();
      const email = ref("");
      const password = ref("");
      const displayName = ref("");

      const handleSubmit = async () => {
        const res = await signup(email.value, password.value, displayName.value);
        if (!error.value) {
          router.push({name: "UserPlaylists"});
        }
      }

      return {email, password, displayName, isPending, error, handleSubmit}
    }
  }
</script>

<style scoped>

</style>

// Other Courses/React/MERN Stack Tutorial/frontend/src/pages/Signup.jsx
import React, { useState } from 'react';
import { useSignup } from "../hooks/useSignup";


const Signup = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const { signup, error, isLoading } = useSignup();

  const handleSubmit = async (e) => {
    e.preventDefault();

    await signup(email, password);
  };

  return (
    <form className="signup" onSubmit={handleSubmit}>
      <h3>Sign up</h3>

      <label>Email:</label>
      <input
        type="email"
        onChange={(e) => setEmail(e.target.value)}
        value={email}
      />

      <label>Password:</label>
      <input
        type="password"
        onChange={(e) => setPassword(e.target.value)}
        value={password}
      />

      <button disabled={isLoading}>Sign up</button>
      {error && <div className="error">{error}</div>}
    </form>
  );
};

export default Signup;
