// Other Courses/Vue Js/Vuex Crash Course - State Management/vuex-todo-manager/src/components/AddTodo.vue
<template>
  <div>
    <h3>Add Todo</h3>
    <div class="add">
      <form @submit.prevent="onSubmit">
        <input type="text" v-model="title" placeholder="Add Todo...">
        <input type="submit" value="Submit">
      </form>
    </div>
  </div>
</template>

<script>
  import {mapActions} from "vuex";


  export default {
    name: "AddTodo",
    data() {
      return {
        title: ""
      }
    },
    methods: {
      ...mapActions(["addTodo"]),

      onSubmit() {
        this.addTodo(this.title);
      }
    }
  }
</script>

<style scoped>
  form {
    display: flex;
  }

  input[type="text"] {
    flex: 10;
    padding: 10px;
    border: 1px solid #41b883;
    outline: 0;
  }

  input[type="submit"] {
    flex: 2;
    background: #41b883;
    color: #fff;
    border: 1px solid #41b883;
    cursor: pointer;
  }
</style>

// Other Courses/Next Js/Next.js Tutorial for Beginners - Next.js 13/next-js-course/server-actions-tutorial/src/app/components/AddTodo.tsx
import { addTodo } from "@/lib/actions"

export default function AddTodo() {

  const content = (
    <form action={addTodo} className="flex gap-2 items-center">

      <input
        type="text"
        name="title"
        className="text-2xl p-1 rounded-lg flex-grow w-full"
        placeholder="New Todo"
        autoFocus
      />

      <button
        type="submit"
        className="p-2 text-xl rounded-2xl text-black border-solid border-black border-2 max-w-xs bg-green-500 hover:cursor-pointer hover:bg-green-400"
      >
        Submit
      </button>

    </form>
  )

  return content
}
