// Other Courses/React/React Authentication with Stytchs NEW SDK - Magic Links with React JS/magic/src/views/Login.jsx
import React from 'react';


const Login = ({ handleLogin }) => {
  const handleSubmit = (e) => {
    e.preventDefault();
    e.stopPropagation();

    const { email } = e.target.elements;
    handleLogin(email.value);
  };

  return (
    <>
      <h1>Login</h1>
      <form onSubmit={handleSubmit}>
        <input type="email" name="email" placeholder="e.g. botken@g.com"/>
        <input type="submit" value="Login"/>
      </form>
    </>
  );
};

export default Login;

// Udemy/Build Web Apps with Vue JS 3 and Firebase/Section 16 - PROJECT BUILD - Muso Ninjas/muso-ninjas/src/views/auth/Login.vue
<template>
  <form @submit.prevent="handleSubmit">
    <h3>Log In</h3>
    <input type="email" placeholder="Email" v-model="email">
    <input type="password" placeholder="Password" v-model="password">
    <div v-if="error" class="error">{{error}}</div>
    <button v-if="!isPending">Log in</button>
    <button v-if="isPending" disabled>Loading</button>
  </form>
</template>

<script>
  import useLogin from "../../composables/useLogin";
  import {ref} from "vue";


  export default {
    name: "Login",
    setup() {
      const {error, login, isPending} = useLogin();
      const email = ref("");
      const password = ref("");

      const handleSubmit = async () => {
        const res = await login(email.value, password.value);
        if (!error.value) {
          console.log("user logged in");
        }
      }

      return {email, password, handleSubmit, error, isPending}
    }
  }
</script>

<style scoped>

</style>
