// Udemy/Build Web Apps with Vue JS 3 and Firebase/Section 10 - Async Code (Composition API)/dojo-blog/src/views/Create.vue
<template>
  <div class="create">
    <form @submit.prevent="handleSubmit">
      <label for="title">Title:</label>
      <input type="text" id="title" v-model="title" required>
      <label for="content">Content:</label>
      <textarea id="content" v-model="body" required></textarea>
      <label for="tags">Tags (hit enter to add a tag)</label>
      <input
          type="text"
          v-model="tag"
          id="tags"
          @keydown.enter.prevent="handleKeyDown"
      >
      <div v-for="tag in tags" :tag="tag" class="pill">
        #{{tag}}
      </div>

      <button>Add Post</button>
    </form>
  </div>
</template>

<script>
  import {ref} from "vue";
  import {useRouter} from "vue-router";


  export default {
    name: "Create",

    setup() {
      const title = ref("");
      const body = ref("");
      const tag = ref("");
      const tags = ref([]);

      const router = useRouter();

      const handleKeyDown = () => {
        if (!tags.value.includes(tag.value)) {
          tag.value = tag.value.replace(/\s/, "");
          tags.value.push(tag.value);
        }
        tag.value = "";
      }

      const handleSubmit = async () => {
        const post = {
          title: title.value,
          body: body.value,
          tags: tags.value
        }

        await fetch("http://localhost:3000/posts", {
          method: "POST",
          headers: {"Content-Type": "application/json"},
          body: JSON.stringify(post)
        })

        router.push({name: "Home"});
      }

      return {title, body, tag, handleKeyDown, tags, handleSubmit}
    }
  }
</script>

<style scoped>
  form {
    max-width: 480px;
    margin: 0 auto;
    text-align: left;
  }

  input, textarea {
    display: block;
    margin: 10px 0;
    width: 100%;
    box-sizing: border-box;
    padding: 10px;
    border: 1px solid #eee;
  }

  textarea {
    height: 160px;
  }

  label {
    display: inline-block;
    margin-top: 30px;
    position: relative;
    font-size: 20px;
    color: white;
    margin-bottom: 10px;
  }

  label::before {
    content: "";
    display: block;
    width: 100%;
    height: 100%;
    background: #ff8800;
    position: absolute;
    z-index: -1;
    padding-right: 40px;
    left: -30px;
    transform: rotateZ(-1.5deg);
  }

  button {
    display: block;
    margin-top: 30px;
    background: #ff8800;
    color: white;
    border: none;
    padding: 8px 16px;
    font-size: 18px
  }

  .pill {
    display: inline-block;
    margin: 10px 10px 0 0;
    color: #444;
    background: #ddd;
    padding: 8px;
    border-radius: 20px;
    font-size: 14px;
  }
</style>

// Other Courses/React/Full Modern React Tutorial/dojo-blog/src/Create.js
import {useState} from "react";
import {useHistory} from "react-router-dom";


const Create = () => {
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [author, setAuthor] = useState("mario");
  const [isPending, setIsPending] = useState(false);
  const history = useHistory();
  

  const handleSubmit = (e) => {
    e.preventDefault();
    const blog = {title, body, author};

    setIsPending(true);

    fetch("http://localhost:8000/blogs", {
      method: "POST",
      headers: {"Content-Type": "application/json"},
      body: JSON.stringify(blog)
    }).then(() => {
      console.log("New blog added");
      setIsPending(false);
      history.push("/");
    })
  };

  return (
    <div className="create">
      <h2>Add a New Blog</h2>
      <form onSubmit={handleSubmit}>
        {/*title*/}
        <label>Blog title:</label>
        <input
          type="text"
          required
          value={title}
          onChange={(e) => setTitle(e.target.value)}
        />
        
        {/*body*/}
        <label>Blog body:</label>
        <textarea
          required
          value={body}
          onChange={(e) => setBody(e.target.value)}
        >
        </textarea>
        
        {/*author*/}
        <label>Blog title:</label>
        <select
          value={author}
          onChange={(e) => setAuthor(e.target.value)}
        >
          <option value="mario">Mario</option>
          <option value="yoshi">Yoshi</option>
        </select>

        {!isPending && <button>Add Blog</button>}
        {isPending && <button disabled>Adding blog...</button>}
      </form>
    </div>
  );
}

export default Create;
